### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by BeckySharp** [clulab/tomcat-text#73]
We really need to clean up the grammars folks.
It's super hard to find actions etc.
We can do one file per action type or something else, but this is not working for me.

We should also remove the `timeIntervals` from the Actions and we can remove all the `removeResearcher` refs (and the corresponding function)

**Comment by remo-help** [comment]
I agree. I'll think about a way to divy up the actions in a sensible way and bring that to you on the Wednesday meeting.

**Comment by adarshp** [comment]
@BeckySharp - what would be a good way for someone to see up-to-date documentation of all the different types of things that are being extracted? This came up in a meeting I had with @ualiangzhang last week. Some options I can think of:

- Maintain a markdown documentation file in the repo with the extraction types and arguments and update it as new extraction types are added or existing ones are modified
- Autogenerate some HTML from the grammar `.yml` files and publish it to the web.
- Add comments to the rules in the grammar files so that they are self-documenting to some extent.

Thoughts?

**Comment by BeckySharp** [comment]
The first is likely prone to straying and the third would be super
unhelpful to the uninitiated.
I like the second.  Further, I like the idea of being able to add some
argument info to the yaml that is enforceable in the grammars.
This is something I'd like to look into, though it would require
modifications to Odin perhaps... or maybe just a wrapper in our app.
at least for now.
Any chance one of our awesome programmers could do option 2 and maybe even
make a hook for it, triggered when merged into master?

**Comment by adarshp** [comment]
@BeckySharp I think option 2 should be possible (including triggering publishing when pull requests are merged into `master`), and I have a high-level sketch in my head about how to do it. I'll keep you posted.

**Comment by BeckySharp** [comment]
closed with #85

**Comment by BeckySharp** [comment]
i'll open a separate issue for the auto-generation of documentation.
