### ISSUE TITLE
MakeCommitment does not recognize some actions

### ISSUE THREAD

**Issue by remo-help** [clulab/tomcat-text#92]
When writing tests for the MakeCommitment rule, I noticed the following issue:

MakeCommitment does not seem to pick out some actions and Im not sure why, I suspect it has to do with the number of dependencies inside the action it's supposed to pick out, but I dont know exactly what's going on.

It picks out:
"I will save this guy."
"I can save this guy."

It does not pick out
I will switch to engineer.
I can switch to engineer.
I can search for a medkit.
I can search for a room.
I can change to engineer.
I can move to the library.

**Comment by BeckySharp** [comment]
this is because the trigger (MD words) gets swallowed up by the arg in a prev step.
One solution/workaround is to _not_ look for agents in the lower/more atomic actions (e.g., Move/Search/etc) and wait for the higher level ones....
e.g., the changes I made here: 
https://github.com/clulab/tomcat-text/compare/no_agent?expand=1
resulting in this:
![image](https://user-images.githubusercontent.com/5384073/118289863-a1532780-b48a-11eb-8d4f-5e289225c2b2.png)
But IDK if this is a good idea.  Another option is to switch from encoding the agent as an arg to encoding it as an attachment.  In the long run this may be a MUCH better option.  We can discuss more.

**Comment by remo-help** [comment]
Maybe we should discuss this in a short meeting, I have some other questions about some of the rules you wrote, I think that will help me make our system more effective, I'll email you about a time

**Comment by remo-help** [comment]
issue closed, implementation will follow as part of issue #98
